[package]
name = "bitonic-sorter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { version = "1.0.*"}

[dev-dependencies]
assert2 = { version = "0.3.*"}